// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// AWSMainRouteTableAssociationConfiguration AWS main route table configuration
// swagger:model AWSMainRouteTableAssociationConfiguration
type AWSMainRouteTableAssociationConfiguration struct {

	// Route table to associate
	RouteTableID string `json:"route_table_id,omitempty"`

	// VPC the route table belongs to
	VpcID string `json:"vpc_id,omitempty"`
}

// Validate validates this a w s main route table association configuration
func (m *AWSMainRouteTableAssociationConfiguration) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AWSMainRouteTableAssociationConfiguration) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AWSMainRouteTableAssociationConfiguration) UnmarshalBinary(b []byte) error {
	var res AWSMainRouteTableAssociationConfiguration
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
