// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// AWSRoute AWS route
// swagger:model AWSRoute
type AWSRoute struct {

	// CIDR block
	CidrBlock string `json:"cidr_block,omitempty"`

	// Gateway ID
	GatewayID string `json:"gateway_id,omitempty"`
}

// Validate validates this a w s route
func (m *AWSRoute) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AWSRoute) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AWSRoute) UnmarshalBinary(b []byte) error {
	var res AWSRoute
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
