// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// AWSSubnetConfiguration AWS subnet configuration
// swagger:model AWSSubnetConfiguration
type AWSSubnetConfiguration struct {

	// Availability zone this subnet belongs to
	AvailabilityZone string `json:"availability_zone,omitempty"`

	// CIDR block for this subnet
	CidrBlock string `json:"cidr_block,omitempty"`

	// AWS tags
	Tags interface{} `json:"tags,omitempty"`

	// VPC this subnet belongs to
	VpcID string `json:"vpc_id,omitempty"`
}

// Validate validates this a w s subnet configuration
func (m *AWSSubnetConfiguration) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AWSSubnetConfiguration) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AWSSubnetConfiguration) UnmarshalBinary(b []byte) error {
	var res AWSSubnetConfiguration
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
