// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// AWSInternetGatewayConfiguration AWS internet gateway configuration
// swagger:model AWSInternetGatewayConfiguration
type AWSInternetGatewayConfiguration struct {

	// AWS tags
	Tags interface{} `json:"tags,omitempty"`

	// VPC this internet gateway belongs to
	VpcID string `json:"vpc_id,omitempty"`
}

// Validate validates this a w s internet gateway configuration
func (m *AWSInternetGatewayConfiguration) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AWSInternetGatewayConfiguration) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AWSInternetGatewayConfiguration) UnmarshalBinary(b []byte) error {
	var res AWSInternetGatewayConfiguration
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
