// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// AzureRMVirtualMachineStorageImageReference azure r m virtual machine storage image reference
// swagger:model AzureRMVirtualMachineStorageImageReference
type AzureRMVirtualMachineStorageImageReference struct {

	// offer
	Offer string `json:"offer,omitempty"`

	// publisher
	Publisher string `json:"publisher,omitempty"`

	// sku
	Sku string `json:"sku,omitempty"`

	// version
	Version string `json:"version,omitempty"`
}

// Validate validates this azure r m virtual machine storage image reference
func (m *AzureRMVirtualMachineStorageImageReference) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AzureRMVirtualMachineStorageImageReference) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AzureRMVirtualMachineStorageImageReference) UnmarshalBinary(b []byte) error {
	var res AzureRMVirtualMachineStorageImageReference
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
