// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// AzureRMVirtualMachineOSProfile azure r m virtual machine o s profile
// swagger:model AzureRMVirtualMachineOSProfile
type AzureRMVirtualMachineOSProfile struct {

	// admin username
	AdminUsername string `json:"admin_username,omitempty"`

	// computer name
	ComputerName string `json:"computer_name,omitempty"`
}

// Validate validates this azure r m virtual machine o s profile
func (m *AzureRMVirtualMachineOSProfile) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AzureRMVirtualMachineOSProfile) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AzureRMVirtualMachineOSProfile) UnmarshalBinary(b []byte) error {
	var res AzureRMVirtualMachineOSProfile
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
