// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// AzureRMSSHKey azure r m SSH key
// swagger:model AzureRMSSHKey
type AzureRMSSHKey struct {

	// key data
	KeyData string `json:"key_data,omitempty"`

	// path
	Path string `json:"path,omitempty"`
}

// Validate validates this azure r m SSH key
func (m *AzureRMSSHKey) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AzureRMSSHKey) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AzureRMSSHKey) UnmarshalBinary(b []byte) error {
	var res AzureRMSSHKey
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
