// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// AzureRMVirtualNetworkConfiguration azure r m virtual network configuration
// swagger:model AzureRMVirtualNetworkConfiguration
type AzureRMVirtualNetworkConfiguration struct {

	// address space
	AddressSpace []string `json:"address_space"`

	// location
	Location string `json:"location,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// resource group name
	ResourceGroupName string `json:"resource_group_name,omitempty"`
}

// Validate validates this azure r m virtual network configuration
func (m *AzureRMVirtualNetworkConfiguration) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AzureRMVirtualNetworkConfiguration) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AzureRMVirtualNetworkConfiguration) UnmarshalBinary(b []byte) error {
	var res AzureRMVirtualNetworkConfiguration
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
