// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// GoogleComputeSubnetworkConfiguration Google compute subnetwork configuration
// swagger:model GoogleComputeSubnetworkConfiguration
type GoogleComputeSubnetworkConfiguration struct {

	// IP CIDR
	IPCidrRange string `json:"ip_cidr_range,omitempty"`

	// Name
	Name string `json:"name,omitempty"`

	// Network
	Network string `json:"network,omitempty"`

	// Project
	Project string `json:"project,omitempty"`

	// Region
	Region string `json:"region,omitempty"`
}

// Validate validates this google compute subnetwork configuration
func (m *GoogleComputeSubnetworkConfiguration) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GoogleComputeSubnetworkConfiguration) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GoogleComputeSubnetworkConfiguration) UnmarshalBinary(b []byte) error {
	var res GoogleComputeSubnetworkConfiguration
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
