// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// GoogleComputeServiceAccount Service account
// swagger:model GoogleComputeServiceAccount
type GoogleComputeServiceAccount struct {

	// Scopes
	Scopes []string `json:"scopes"`
}

// Validate validates this google compute service account
func (m *GoogleComputeServiceAccount) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GoogleComputeServiceAccount) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GoogleComputeServiceAccount) UnmarshalBinary(b []byte) error {
	var res GoogleComputeServiceAccount
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
