// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// GoogleComputeSubnetwork Google compute subnetwork
// swagger:model GoogleComputeSubnetwork
type GoogleComputeSubnetwork interface{}
