// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// GoogleComputeFirewallConfiguration Google compute firewall configuration
// swagger:model GoogleComputeFirewallConfiguration
type GoogleComputeFirewallConfiguration struct {

	// Allow rules
	Allow interface{} `json:"allow,omitempty"`

	// Name
	Name string `json:"name,omitempty"`

	// Network
	Network string `json:"network,omitempty"`

	// Project
	Project string `json:"project,omitempty"`

	// Source ranges
	SourceRanges []string `json:"source_ranges"`

	// Target tags
	TargetTags []string `json:"target_tags"`
}

// Validate validates this google compute firewall configuration
func (m *GoogleComputeFirewallConfiguration) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GoogleComputeFirewallConfiguration) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GoogleComputeFirewallConfiguration) UnmarshalBinary(b []byte) error {
	var res GoogleComputeFirewallConfiguration
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
