// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// GoogleComputeInstanceConfiguration Google compute instance configuration
// swagger:model GoogleComputeInstanceConfiguration
type GoogleComputeInstanceConfiguration struct {

	// Boot disk
	BootDisk *GoogleComputeBootDiskConfiguration `json:"boot_disk,omitempty"`

	// Machine type
	MachineType string `json:"machine_type,omitempty"`

	// Network interface
	NetworkInterface *GoogleComputeNetworkInterface `json:"network_interface,omitempty"`

	// Project
	Project string `json:"project,omitempty"`

	// Service account
	ServiceAccount *GoogleComputeServiceAccount `json:"service_account,omitempty"`

	// Tags
	Tags []string `json:"tags"`

	// Zone
	Zone string `json:"zone,omitempty"`
}

// Validate validates this google compute instance configuration
func (m *GoogleComputeInstanceConfiguration) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBootDisk(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNetworkInterface(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateServiceAccount(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GoogleComputeInstanceConfiguration) validateBootDisk(formats strfmt.Registry) error {

	if swag.IsZero(m.BootDisk) { // not required
		return nil
	}

	if m.BootDisk != nil {
		if err := m.BootDisk.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("boot_disk")
			}
			return err
		}
	}

	return nil
}

func (m *GoogleComputeInstanceConfiguration) validateNetworkInterface(formats strfmt.Registry) error {

	if swag.IsZero(m.NetworkInterface) { // not required
		return nil
	}

	if m.NetworkInterface != nil {
		if err := m.NetworkInterface.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("network_interface")
			}
			return err
		}
	}

	return nil
}

func (m *GoogleComputeInstanceConfiguration) validateServiceAccount(formats strfmt.Registry) error {

	if swag.IsZero(m.ServiceAccount) { // not required
		return nil
	}

	if m.ServiceAccount != nil {
		if err := m.ServiceAccount.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("service_account")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *GoogleComputeInstanceConfiguration) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GoogleComputeInstanceConfiguration) UnmarshalBinary(b []byte) error {
	var res GoogleComputeInstanceConfiguration
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
