// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// GoogleComputeNetworkInterface Network interface
// swagger:model GoogleComputeNetworkInterface
type GoogleComputeNetworkInterface struct {

	// access config
	AccessConfig interface{} `json:"access_config,omitempty"`

	// subnetwork
	Subnetwork string `json:"subnetwork,omitempty"`

	// subnetwork project
	SubnetworkProject string `json:"subnetwork_project,omitempty"`
}

// Validate validates this google compute network interface
func (m *GoogleComputeNetworkInterface) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GoogleComputeNetworkInterface) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GoogleComputeNetworkInterface) UnmarshalBinary(b []byte) error {
	var res GoogleComputeNetworkInterface
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
