// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// GoogleComputeNetwork Google compute network
// swagger:model GoogleComputeNetwork
type GoogleComputeNetwork interface{}
