// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// GoogleComputeNetworkConfiguration Google compute network configuration
// swagger:model GoogleComputeNetworkConfiguration
type GoogleComputeNetworkConfiguration struct {

	// Auto create subnetworks
	AutoCreateSubnetworks bool `json:"auto_create_subnetworks,omitempty"`

	// Description
	Description string `json:"description,omitempty"`

	// Name
	Name string `json:"name,omitempty"`

	// Project
	Project string `json:"project,omitempty"`
}

// Validate validates this google compute network configuration
func (m *GoogleComputeNetworkConfiguration) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GoogleComputeNetworkConfiguration) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GoogleComputeNetworkConfiguration) UnmarshalBinary(b []byte) error {
	var res GoogleComputeNetworkConfiguration
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
