// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// GoogleComputeBootDiskConfiguration Boot disk configuration
// swagger:model GoogleComputeBootDiskConfiguration
type GoogleComputeBootDiskConfiguration struct {

	// Initialize parameters
	InitializeParams *GoogleComputeBootDiskConfigurationInitializeParams `json:"initialize_params,omitempty"`
}

// Validate validates this google compute boot disk configuration
func (m *GoogleComputeBootDiskConfiguration) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateInitializeParams(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GoogleComputeBootDiskConfiguration) validateInitializeParams(formats strfmt.Registry) error {

	if swag.IsZero(m.InitializeParams) { // not required
		return nil
	}

	if m.InitializeParams != nil {
		if err := m.InitializeParams.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("initialize_params")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *GoogleComputeBootDiskConfiguration) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GoogleComputeBootDiskConfiguration) UnmarshalBinary(b []byte) error {
	var res GoogleComputeBootDiskConfiguration
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
