// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// NodeAddresses node addresses
// swagger:model NodeAddresses
type NodeAddresses struct {

	// External IP
	ExternalIP string `json:"external_ip,omitempty"`

	// Internal IP
	InternalIP string `json:"internal_ip,omitempty"`
}

// Validate validates this node addresses
func (m *NodeAddresses) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NodeAddresses) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NodeAddresses) UnmarshalBinary(b []byte) error {
	var res NodeAddresses
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
