// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// NodePoolAutoscalingScalingStrategy node pool autoscaling scaling strategy
// swagger:model NodePoolAutoscalingScalingStrategy
type NodePoolAutoscalingScalingStrategy struct {

	// scale down
	ScaleDown string `json:"scale_down,omitempty"`

	// scale up
	ScaleUp string `json:"scale_up,omitempty"`
}

// Validate validates this node pool autoscaling scaling strategy
func (m *NodePoolAutoscalingScalingStrategy) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NodePoolAutoscalingScalingStrategy) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NodePoolAutoscalingScalingStrategy) UnmarshalBinary(b []byte) error {
	var res NodePoolAutoscalingScalingStrategy
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
