// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// TemplateProvider Provider for a template
// swagger:model TemplateProvider
type TemplateProvider map[string]TemplateProviderConfiguration

// Validate validates this template provider
func (m TemplateProvider) Validate(formats strfmt.Registry) error {
	return nil
}
