// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PluginPluginsCompatibility Defines the Plugin required and what versions are compatible with this version of the parent plugin
// swagger:model PluginPluginsCompatibility
type PluginPluginsCompatibility struct {

	// The implementation name for the type of plugin
	// Required: true
	Implementation *string `json:"implementation"`

	// The maximum plugin version
	// Required: true
	Max *string `json:"max"`

	// The minimum plugin version
	// Required: true
	Min *string `json:"min"`
}

// Validate validates this plugin plugins compatibility
func (m *PluginPluginsCompatibility) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateImplementation(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMax(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMin(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PluginPluginsCompatibility) validateImplementation(formats strfmt.Registry) error {

	if err := validate.Required("implementation", "body", m.Implementation); err != nil {
		return err
	}

	return nil
}

func (m *PluginPluginsCompatibility) validateMax(formats strfmt.Registry) error {

	if err := validate.Required("max", "body", m.Max); err != nil {
		return err
	}

	return nil
}

func (m *PluginPluginsCompatibility) validateMin(formats strfmt.Registry) error {

	if err := validate.Required("min", "body", m.Min); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PluginPluginsCompatibility) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PluginPluginsCompatibility) UnmarshalBinary(b []byte) error {
	var res PluginPluginsCompatibility
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
