// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PluginKubernetesCompatibility Defines the Kubernetes version that the plugin supports
// swagger:model PluginKubernetesCompatibility
type PluginKubernetesCompatibility struct {

	// The maximum Kubernetes version for the plugin
	// Required: true
	Max *string `json:"max"`

	// The minimum Kubernetes version for the plugin
	// Required: true
	Min *string `json:"min"`
}

// Validate validates this plugin kubernetes compatibility
func (m *PluginKubernetesCompatibility) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMax(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMin(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PluginKubernetesCompatibility) validateMax(formats strfmt.Registry) error {

	if err := validate.Required("max", "body", m.Max); err != nil {
		return err
	}

	return nil
}

func (m *PluginKubernetesCompatibility) validateMin(formats strfmt.Registry) error {

	if err := validate.Required("min", "body", m.Min); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PluginKubernetesCompatibility) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PluginKubernetesCompatibility) UnmarshalBinary(b []byte) error {
	var res PluginKubernetesCompatibility
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
