// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// User A user belonging to an organization
// swagger:model User
type User struct {

	// Timestamp at which the user was created
	// Required: true
	AddedAt *string `json:"added_at"`

	// Avatar URL
	// Required: true
	AvatarURL *string `json:"avatar_url"`

	// User email
	// Required: true
	Email *string `json:"email"`

	// User ID
	// Required: true
	ID UUID `json:"id"`

	// User name
	// Required: true
	Name *string `json:"name"`

	// SSH Keys
	// Required: true
	SSHKeys SSHKeys `json:"ssh_keys"`
}

// Validate validates this user
func (m *User) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAddedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateAvatarURL(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEmail(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSSHKeys(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *User) validateAddedAt(formats strfmt.Registry) error {

	if err := validate.Required("added_at", "body", m.AddedAt); err != nil {
		return err
	}

	return nil
}

func (m *User) validateAvatarURL(formats strfmt.Registry) error {

	if err := validate.Required("avatar_url", "body", m.AvatarURL); err != nil {
		return err
	}

	return nil
}

func (m *User) validateEmail(formats strfmt.Registry) error {

	if err := validate.Required("email", "body", m.Email); err != nil {
		return err
	}

	return nil
}

func (m *User) validateID(formats strfmt.Registry) error {

	if err := m.ID.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("id")
		}
		return err
	}

	return nil
}

func (m *User) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *User) validateSSHKeys(formats strfmt.Registry) error {

	if err := validate.Required("ssh_keys", "body", m.SSHKeys); err != nil {
		return err
	}

	if err := m.SSHKeys.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("ssh_keys")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *User) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *User) UnmarshalBinary(b []byte) error {
	var res User
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
